baseURL = "https://iizz0op.github.io/blog/"
locale = "zh-cn"
defaultContentLanguage = "zh"
title = "iizz0op"
theme = "hugo-theme-stack"
hasCJKLanguage = true

[pagination]
pagerSize = 8

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = ["post"]
rssFullContent = true

[params.sidebar]
avatar = "/blog/img/avatar.png"
emoji = "🌱"
subtitle = "To be a scientist who discovers, and an engineer who builds."

[params.article]
toc = true
readingTime = true

[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[params.comments]
enabled = false

[params.widgets]
homepage = [
    { type = "search" },
    { type = "tag-cloud", params = { limit = 10 } },
    { type = "categories", params = { limit = 10 } },
    { type = "archives", params = { limit = 5 } },
]
page = [{ type = "toc" }]

[[menu.main]]
identifier = "home"
name = "主页"
pageRef = "/"
weight = 10

[menu.main.params]
icon = "home"

[[menu.main]]
identifier = "posts"
name = "文章"
pageRef = "/post"
weight = 20

[menu.main.params]
icon = "archives"

[[menu.main]]
identifier = "search"
name = "搜索"
pageRef = "/page/search"
weight = 30

[menu.main.params]
icon = "search"

[[menu.main]]
identifier = "about"
name = "关于"
pageRef = "/page/about"
weight = 40

[menu.main.params]
icon = "user"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/iizz0op"

[menu.social.params]
icon = "brand-github"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true

[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = true
